#!/bin/bash

shopt -s nullglob
shopt -s nocasematch

BASEDIR=${HOME}/msdk_code_repos

if [ -u $1 ] ; then
    ls -1 $BASEDIR
    exit 0
elif [ $1 == "help" ] ; then
     echo "USAGE: $0 [(<string> | (grep|-) <regex> | (glob|.) <glob>)]"
     echo
     echo "    Lists the possible options for modular repo instances that can be selected"
     echo
     exit 1
fi

# store the current directory so we can return to it
CUR_DIR=$(pwd)

# move to and attempt to match the string as a search in the code directory
cd $BASEDIR

# determine whether argument 1 was just a case sensitive string we want to find,
# or whether it was specifying whether we want to use argument 2 as a glob or
# grep search
case "$1" in
     "grep" | "-" )
        MATCH_MSDK=$(ls -d -1 * | grep -e "$2") ;;
     "glob" | "." )
        MATCH_MSDK=$(ls -d ${2})  ;;
     *)
        MATCH_MSDK=$(ls -d *${1}*)
esac

printf '%s\n' "${MATCH_MSDK[@]}"

# return to the original directory now that we're done in the different directory
cd $CUR_DIR
